#Copyright (c) 2019-2023 Andreas Bauer
#SPDX-License-Identifier: MIT
version: '3'
services:
  user-service:
    build:
      context: .
    image: simple-go-user-service:latest
    ports:
      - "8080:8080"
    environment:
      - MONGO_HOSTNAME=mongodb
      - MONGO_USERNAME=admin
      - MONGO_PASSWORD=admin
      - MONGO_AUTH_DATABASE=admin
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
      - MONGO_INITDB_DATABASE=admin